apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: 4-3-k8sapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: k8sapp-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: "mysql+pymysql://appuser:apppassword@db-service:3306/k8sappdb"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10